In [2]:
from sklearn.datasets import load_digits, load_breast_cancer

dataset = load_breast_cancer()
X = dataset.data
y = dataset.target

print X

[[  1.79900000e+01   1.03800000e+01   1.22800000e+02 ...,   2.65400000e-01
    4.60100000e-01   1.18900000e-01]
 [  2.05700000e+01   1.77700000e+01   1.32900000e+02 ...,   1.86000000e-01
    2.75000000e-01   8.90200000e-02]
 [  1.96900000e+01   2.12500000e+01   1.30000000e+02 ...,   2.43000000e-01
    3.61300000e-01   8.75800000e-02]
 ..., 
 [  1.66000000e+01   2.80800000e+01   1.08300000e+02 ...,   1.41800000e-01
    2.21800000e-01   7.82000000e-02]
 [  2.06000000e+01   2.93300000e+01   1.40100000e+02 ...,   2.65000000e-01
    4.08700000e-01   1.24000000e-01]
 [  7.76000000e+00   2.45400000e+01   4.79200000e+01 ...,   0.00000000e+00
    2.87100000e-01   7.03900000e-02]]


In [1]:
from sklearn.cross_validation import cross_val_score
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

In [3]:
gnb = GaussianNB()
bnb = BernoulliNB()
mnb = MultinomialNB()

fraction = 0.8
L = len(X)
count = int(fraction * L)
X_train = X[:count]
y_train = y[:count]

X_test = X[count:]
y_test = y[count:]

In [5]:
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print sum(y_test == y_pred) / float(len(y_test))

0.956140350877


In [4]:
import numpy as np
alphas = np.logspace(-4, -.5, 30)

scores = list()
scores_std = list()

for alpha in alphas:
    gnb.alpha = alpha
    this_scores = cross_val_score(gnb, X, y, n_jobs=1)
    scores.append(np.mean(this_scores))
    scores_std.append(np.std(this_scores))

In [10]:
print this_scores
print scores
print scores_std

[ 0.91578947  0.94736842  0.94708995]
[0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297, 0.9367492806089297]
[0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821257631705975, 0.014821

In [15]:
score = cross_val_score(gnb, X, y)
print score
score = cross_val_score(bnb, X, y)
print score
score = cross_val_score(mnb, X, y)
print score

[ 0.91578947  0.94736842  0.94708995]
[ 0.62631579  0.62631579  0.62962963]
[ 0.87894737  0.89473684  0.91005291]


In [18]:
digit = load_digits()
Xd = digit.data
yd = digit.target
score = cross_val_score(gnb, Xd, yd)
print score
score = cross_val_score(bnb, Xd, yd)
print score
score = cross_val_score(mnb, Xd, yd)
print score

[ 0.82392027  0.79966611  0.83221477]
[ 0.83554817  0.80467446  0.83724832]
[ 0.8820598   0.85976628  0.87080537]


In [15]:
import pandas as pd

In [16]:
data_text = pd.read_csv('datatraining.txt')

In [17]:
print data_text

                     date  Temperature   Humidity  Light         CO2  \
1     2015-02-04 17:51:00    23.180000  27.272000  426.0  721.250000   
2     2015-02-04 17:51:59    23.150000  27.267500  429.5  714.000000   
3     2015-02-04 17:53:00    23.150000  27.245000  426.0  713.500000   
4     2015-02-04 17:54:00    23.150000  27.200000  426.0  708.250000   
5     2015-02-04 17:55:00    23.100000  27.200000  426.0  704.500000   
6     2015-02-04 17:55:59    23.100000  27.200000  419.0  701.000000   
7     2015-02-04 17:57:00    23.100000  27.200000  419.0  701.666667   
8     2015-02-04 17:57:59    23.100000  27.200000  419.0  699.000000   
9     2015-02-04 17:58:59    23.100000  27.200000  419.0  689.333333   
10    2015-02-04 18:00:00    23.075000  27.175000  419.0  688.000000   
11    2015-02-04 18:01:00    23.075000  27.150000  419.0  690.250000   
12    2015-02-04 18:02:00    23.100000  27.100000  419.0  691.000000   
13    2015-02-04 18:03:00    23.100000  27.166667  419.0  683.50

In [18]:
data_text = data_text.drop('date', axis = 1)

In [19]:
y = data_text['Occupancy']

X = data_text.drop('Occupancy', axis = 1)

In [20]:
score = cross_val_score(gnb, X, y)
print score
score = cross_val_score(bnb, X, y)
print score
score = cross_val_score(mnb, X, y)
print score

[ 0.96979742  0.95394252  0.97236551]
[ 0.95248619  0.71849668  0.866986  ]
[ 0.9694291   0.85851142  0.95946942]
